Repository UBC-MDS/encoderPy, pull requests merged in 2020-03, with the labels that each got.

#41 Fix readme to remove catboost_encoder.
  README.md
  encoderpy/catboost_encoder.py
Labels: documentation

#43 Target Encoder: add initial code and unit test
  encoderpy/target_encoder.py
  tests/test_target_encoder.py
Labels: enhancement, individual, python

#48 Add comments for test_target_encoder script
  tests/test_target_encoder.py
Labels: enhancement, individual, python

#47 Complete the implementation of conjugate_encoder.py and the respective tests for it, and update README.md
  README.html
  README.md
  docs/source/encoderpy.rst
  encoderpy/conjugate_encoder.py
  poetry.lock
  pyproject.toml
  tests/test_conjugate_encoder.py
Labels: enhancement, python

#49 Bronwyn frequency encoder
  encoderpy/frequency_encoder.py
  poetry.lock
  tests/test_frequency_encoder.py
Labels: enhancement, python

#50 Fix minor bugs to pass tests in frequency_encoder.py
  README.md
  encoderpy/frequency_encoder.py
  poetry.lock
  pyproject.toml
Labels: bug

#58 Change the output type to list #54
  encoderpy/target_encoder.py
  tests/test_target_encoder.py
Labels: individual, python

#59 Fix all tests and functions to pass flake8 checks (PEP8 styling)
  docs/conf.py
  encoderpy/conjugate_encoder.py
  encoderpy/frequency_encoder.py
  encoderpy/onehot_encoder.py
  encoderpy/target_encoder.py
  poetry.lock
  pyproject.toml
  tests/test_conjugate_encoder.py
  tests/test_encoderpy.py
  tests/test_frequency_encoder.py
  tests/test_target_encoder.py
Labels: bug, documentation, python

#63 Initial CI for build.yml
  .github/workflows/build.yml
  poetry.lock
  pyproject.toml
Labels: enhancement, python

#64 CI passing for build.yml
  encoderpy/onehot_encoder.py
  tests/test_frequency_encoder.py
  tests/test_one_hot_encoder.py
  tests/test_target_encoder.py
Labels: bug

#66 Add dependency python-semantic-release
  poetry.lock
  pyproject.toml
Labels: bug, enhancement

#68 Address flake8 build failure
  encoderpy/onehot_encoder.py
  tests/test_onehot_encoder.py
Labels: bug, python

#69 Add vignette to readme, bump version for "feat"
  README.html
  README.md
  tests/test_one_hot_encoder.py
Labels: bug, documentation

#77 Add inline comments for all functions
  encoderpy/conjugate_encoder.py
  encoderpy/onehot_encoder.py
  tests/test_frequency_encoder.py
Labels: documentation

#78 Change installation instructions to install dependecies, change installation.rst to link to correct repo
  README.html
  README.md
  docs/installation.rst
Labels: documentation
